### ISSUE TITLE
tutorial on how to create R-independent infographiq

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiqR#58]
Open `infographiq.Rproj` to launch RStudio in that working directory. Then create a vignette, aka article via:

```r
# create article (once)
usethis::use_vignette("standalone-html", "Building a Standalone HTML Infographiq")

# knit articles (iteratively)
pkgdown::build_articles()

# build all (once before commit)
pkgdown::build_site()
```

Also see the [devtools cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/package-development.pdf), noting that many functions have moved from devtools:: to usethis::.

**Comment by bbest** [comment]
@7yl4r, also check out @superjai's awesome infographiq demo showing effect of different arguments to JS function `link_svg()`:

https://marinebon.org/infographiq/infographiq-demonstration.html

![image](https://user-images.githubusercontent.com/2837257/116907677-bdd3a200-abf6-11eb-908b-2593577caeda.png)

**Comment by 7yl4r** [comment]
I think @superjai 's excellent docs have covered this well and I have neglected this issue. If there is still a blindspot please reopen and let me know how to help.
