### ISSUE TITLE
Should infographiqR repo exist?

### ISSUE THREAD

**Issue by superjai** [marinebon/infographiqR#63]
Hey @bbest - I have completed the rewrite of the infographiq javascript and the reorganization of cinms. After doing all of this, it doesn't seem like that the infographiqR repo serves much purpose.

Here's the reasoning. You have drawn a clear distinction between 1) the code needed to generate the infographic itself and 2) the code generating the modal windows. To this end, you split nms4r into two repos, with the repos containing the following r files: 
- infographiqR (infographic generation)
  - render_rmd.R
- onmsR (modal window generation)
    - calcofi.R
    - calculate_data.R
    - spatial.R
    - utils-pipe.R

If you take a look at the functions contained within the original [render_rmd.R](https://github.com/marinebon/infographiqR/blob/5a8714694fc8df418dc9b8c7b191a80f6fb6a283/R/render_rmd.R), you'll see that almost all of them have to do with modal window generation, not infographic generation:
- `calcofi_map`: modal window generation only
- `calcofi_plot`: modal window generation only
- `calculate_SST_anomaly`: modal window generation only
- `calculate_statistics`: modal window generation only
- `generate_html_4_rmd`: modal window generation only
- `get_dates`: modal window generation only
- `get_figure_info`: modal window generation only
- `get_nms_polygons`: modal window generation only
- `map_nms_sites`: modal window generation only
- `md_caption`: modal window generation only
- `plot_SST_anomaly`: modal window generation only
- `plot_intertidal_nms`: modal window generation only
- `plot_metric_timeseries`: modal window generation only
- `ply2erddap`: modal window generation only
- `render_all_rmd`: modal window generation only
- `render_figure`: modal window generation only
- `create_website`: infographic generation only
- `get_modal_info`: modal window AND infographic generation 

You can see that only the last two functions `create_website` and `get_modal_info` of the 18 total have anything at all to do with infographic generation. Consequently, I moved the 16 other functions into onmsR into a R file called [render_modal.R](https://github.com/noaa-onms/onmsR/blob/master/R/render_modal.R).

So that leaves us with two functions in [render_rmd.R](https://github.com/marinebon/infographiqR/blob/master/R/render_rmd.R) in infographiqR. And I would argue that these shouldn't be here either. 
- `create_website` should be deleted. This is a simple function I wrote to copy a working template version of the infographic from the inst folder to whatever folder the user wants. The thing though is that the same functionality can be achieved by including a hyperlink to a  zip file of the working template in the tutorial materials. 
- `get_modal_info` should really be moved to onmsR. Though used to generate camera and info icons above the infographic, it is primarily used for generating those icons within the modal window.

**Comment by bbest** [comment]
I appreciate these points Jai, but let's distinguish between these repositories for different aspects of interactive infographic creation and maintenance:

1. **infographiqJS**: open a modal or new window from icons in SVG or link in table of contents; and stops short of how to populate the modal window.

2. **onmsR**: dataset-specific wrangling and visualization for populating into the modal windows, but could also be used outside of any interactive infographic generation altogether, ie static or dynamic Condition Reports, etc.

2. **infographiqR**: support functions in R to generate interactive infographic websites, such as creating a simple Rmarkdown website of infographics, using a glossary to generate tooltips, populating modal templates from Google Sheets with fontawesome icons and links, etc.
