### ISSUE TITLE
fold new authorized googlesheet4 reading into functions

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiqR#65]
Fold functionality of [noaa-onms/ocnms: test_gs4_auth.Rmd](https://github.com/noaa-onms/ocnms/blob/bfd52b253742bd9cce7d2654dfd09f96299a8907/test_gs4_auth.Rmd) into functions for reading in a private GoogleSheet shared with `shares@nms4gargle.iam.gserviceaccount.com` using a JSON file for authentication:

```r
librarian::shelf(DT, googlesheets4, here)

gsheets_sa_json <- switch(
  Sys.info()[["effective_user"]],
  bbest      = "/Volumes/GoogleDrive/My Drive/projects/nms-web/data/nms4gargle-774a9e9ec703.json",
  jai        = "/Volumes/GoogleDrive/My Drive/service-tokens/nms4gargle-774a9e9ec703.json",
  PikesStuff = "/Users/PikesStuff/Theseus/Private/nms4gargle-774a9e9ec703.json")

gsheet <- "https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit"
```

## Setup Service Account API Key

Reference:

- [googlesheets4 auth • googlesheets4](https://googlesheets4.tidyverse.org/articles/articles/auth.html)
- [Non-interactive auth](https://cran.r-project.org/web/packages/gargle/vignettes/non-interactive-auth.html): main reference for understanding this

Steps:

1. Save [nms4gargle-774a9e9ec703](https://drive.google.com/file/d/1LTvMM74gYB5MAkspiTqjA4BiTzVLTgNp/view?usp=sharing) locally, in this case to `r gsheets_sa_json`.

  1. Manage [shares – IAM & Admin – nms4gargle – Google Cloud Platform](https://console.cloud.google.com/iam-admin/serviceaccounts/details/111162214432618062602?authuser=2&project=nms4gargle). Added permissions to : jai.ranganathan@gmail.com, pike.spector@noaa.gov.
  
1. Share [Master_OCNMS_infographic_content - Google Sheets](`r gsheet`) to `shares@nms4gargle.iam.gserviceaccount.com`.

## Use

```{r}
# ensure secret JSON file exists
stopifnot(file.exists(gsheets_sa_json))

# authenticate to GoogleSheets using Google Service Account's secret JSON
gs4_auth(path = gsheets_sa_json)

# access to this Google Sheet was granted to the Google Service Account
#   by Sharing with its email: shares@nms4gargle.iam.gserviceaccount.com
sheet_names(gsheet)
```

**Comment by superjai** [comment]
Create new R script file to hold new Google Sheet functionalities: [ocnms_render_rmd.R](https://github.com/marinebon/infographiqR/blob/master/R/ocnms_render_rmd.R)

New functions:

- [ocnms_get_sheet](https://github.com/marinebon/infographiqR/blob/522fce0d7b1567df4bbb6548df3a71856b5a39ed/R/ocnms_render_rmd.R#L52): folds in functionality of [noaa-onms/ocnms: test_gs4_auth.Rmd ](https://github.com/noaa-onms/ocnms/blob/bfd52b253742bd9cce7d2654dfd09f96299a8907/test_gs4_auth.Rmd)
- [ocnms_create_link_table](https://github.com/marinebon/infographiqR/blob/522fce0d7b1567df4bbb6548df3a71856b5a39ed/R/ocnms_render_rmd.R#L82): create Infographiq link table from protected google sheet
- [ocnms_get_modal_info](https://github.com/marinebon/infographiqR/blob/522fce0d7b1567df4bbb6548df3a71856b5a39ed/R/ocnms_render_rmd.R#L14): updating of InfographiqR get_modal_info function to account for new table structure for the google sheet of OCNMS
